// <auto-generated />
using System;
using BlazorChatApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorChatApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260213110435_dev_v1_260213_JC1")]
    partial class dev_v1_260213_JC1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatMembers.ChatMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMembers");

                    b.HasDiscriminator().HasValue("ChatMember");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatMembers.ChatMemberRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatMemberRoles");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Owner"
                        });
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatRequests.ChatRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChatRequestStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("InitializerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitedId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatRequestStatusId");

                    b.HasIndex("InitializerId");

                    b.HasIndex("InvitedId");

                    b.ToTable("ChatRequests");

                    b.HasDiscriminator().HasValue("ChatRequest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatRequests.ChatRequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChatRequestStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusCode = "Created"
                        },
                        new
                        {
                            Id = 2,
                            StatusCode = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            StatusCode = "Decline"
                        });
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.Chats.ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.ToTable("ChatRoom");

                    b.HasDiscriminator().HasValue("ChatRoom");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ChatMemberId");

                    b.ToTable("Messages");

                    b.HasDiscriminator().HasValue("Message");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ProfilePhoto")
                        .HasColumnType("bytea");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatMembers.GroupChatMember", b =>
                {
                    b.HasBaseType("BlazorChatApp.Domain.Models.ChatMembers.ChatMember");

                    b.Property<int>("ChatMemberRoleId")
                        .HasColumnType("integer");

                    b.HasIndex("ChatMemberRoleId");

                    b.HasDiscriminator().HasValue("GroupChatMember");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatRequests.FriendRequest", b =>
                {
                    b.HasBaseType("BlazorChatApp.Domain.Models.ChatRequests.ChatRequest");

                    b.HasDiscriminator().HasValue("FriendRequest");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatRequests.GroupChatRequest", b =>
                {
                    b.HasBaseType("BlazorChatApp.Domain.Models.ChatRequests.ChatRequest");

                    b.Property<Guid>("GroupChatRoomId")
                        .HasColumnType("uuid");

                    b.HasIndex("GroupChatRoomId");

                    b.HasDiscriminator().HasValue("GroupChatRequest");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.Chats.DirectChatRoom", b =>
                {
                    b.HasBaseType("BlazorChatApp.Domain.Models.Chats.ChatRoom");

                    b.HasDiscriminator().HasValue("DirectChatRoom");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.Chats.GroupChatRoom", b =>
                {
                    b.HasBaseType("BlazorChatApp.Domain.Models.Chats.ChatRoom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasDiscriminator().HasValue("GroupChatRoom");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.Messages.PhotoMessage", b =>
                {
                    b.HasBaseType("BlazorChatApp.Domain.Models.Messages.Message");

                    b.Property<byte[]>("Photo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasDiscriminator().HasValue("PhotoMessage");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatMembers.ChatMember", b =>
                {
                    b.HasOne("BlazorChatApp.Domain.Models.Chats.ChatRoom", "Chat")
                        .WithMany("ChatMembers")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorChatApp.Domain.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatRequests.ChatRequest", b =>
                {
                    b.HasOne("BlazorChatApp.Domain.Models.ChatRequests.ChatRequestStatus", "ChatRequestStatus")
                        .WithMany()
                        .HasForeignKey("ChatRequestStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorChatApp.Domain.Models.Users.User", "Initializer")
                        .WithMany()
                        .HasForeignKey("InitializerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorChatApp.Domain.Models.Users.User", "Invited")
                        .WithMany()
                        .HasForeignKey("InvitedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRequestStatus");

                    b.Navigation("Initializer");

                    b.Navigation("Invited");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.Messages.Message", b =>
                {
                    b.HasOne("BlazorChatApp.Domain.Models.Chats.ChatRoom", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorChatApp.Domain.Models.ChatMembers.ChatMember", "ChatMember")
                        .WithMany()
                        .HasForeignKey("ChatMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("ChatMember");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatMembers.GroupChatMember", b =>
                {
                    b.HasOne("BlazorChatApp.Domain.Models.ChatMembers.ChatMemberRole", "ChatMemberRole")
                        .WithMany()
                        .HasForeignKey("ChatMemberRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatMemberRole");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.ChatRequests.GroupChatRequest", b =>
                {
                    b.HasOne("BlazorChatApp.Domain.Models.Chats.GroupChatRoom", "GroupChatRoom")
                        .WithMany()
                        .HasForeignKey("GroupChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupChatRoom");
                });

            modelBuilder.Entity("BlazorChatApp.Domain.Models.Chats.ChatRoom", b =>
                {
                    b.Navigation("ChatMembers");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
